[2024-06-08 14:50:30,230: INFO/MainProcess] Celery worker started
[2024-06-08 14:50:30,444: WARNING/MainProcess] /home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-06-08 14:50:30,452: INFO/MainProcess] Connected to redis://10.10.1.63:6379/0
[2024-06-08 14:50:30,453: WARNING/MainProcess] /home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-06-08 14:50:30,457: INFO/MainProcess] mingle: searching for neighbors
[2024-06-08 14:50:31,469: INFO/MainProcess] mingle: all alone
[2024-06-08 14:50:31,484: INFO/MainProcess] celery@cerelabs004 ready.
[2024-06-08 14:53:01,253: INFO/MainProcess] Task scrap_results[970f50f7-730f-448e-96e2-1143fdc414f6] received
[2024-06-08 14:53:01,254: INFO/ForkPoolWorker-2] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='Mumbai restaurant menu card', use_cse_papi=True, max_links=10)", 'db': {'id': 5, 'scrap_query': 'Mumbai restaurant menu card', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 9, 22, 57), 'updated_at': datetime.datetime(2024, 6, 8, 9, 22, 57)}}
[2024-06-08 14:53:02,094: INFO/ForkPoolWorker-2] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='Mumbai restaurant menu card', use_cse_papi=True, max_links=10)", 'db': {'id': 5, 'scrap_query': 'Mumbai restaurant menu card', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 9, 22, 57), 'updated_at': datetime.datetime(2024, 6, 8, 9, 22, 57)}}
[2024-06-08 14:53:02,146: WARNING/ForkPoolWorker-2] An error occurred: HTTPSConnectionPool(host='preview.redd.it', port=443): Max retries exceeded with url: /z909ykr8s1sb1.jpg?auto=webp&s=bc4b62ee2c1df5f181edcdb6fffa9ff99f6dd8ea (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 14:53:02,200: WARNING/ForkPoolWorker-2] An error occurred: HTTPSConnectionPool(host='i.redd.it', port=443): Max retries exceeded with url: /menu-of-an-irani-restaurant-in-mumbai-this-is-considered-v0-jtmishzc4n4a1.jpg?width=3024&format=pjpg&auto=webp&s=af36b5f4da0cea9ac685b69c7c9e9ea3315f5a3c (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 14:53:02,269: WARNING/ForkPoolWorker-2] An error occurred: HTTPSConnectionPool(host='media.cntraveller.com', port=443): Max retries exceeded with url: /photos/611bf4afdb797d0116fd51b0/16:9/w_2580,c_limit/the-taj-mahal-palace-mumbai-india-conde-nast-traveller-28march15-pr_2.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 14:53:02,331: WARNING/ForkPoolWorker-2] An error occurred: HTTPSConnectionPool(host='online.fliphtml5.com', port=443): Max retries exceeded with url: /lkvwf/rohz/files/large/3e361588b6bb325168f5f0435ac80488.jpg?1671084173 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 14:53:02,939: WARNING/ForkPoolWorker-2] An error occurred: HTTPSConnectionPool(host='mumbaihousecuisine.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/09/mhc-logo-1-e1663987449842.png (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 14:53:02,943: INFO/ForkPoolWorker-2] Task scrap_results[970f50f7-730f-448e-96e2-1143fdc414f6] succeeded in 1.6895650459991884s: None
[2024-06-08 15:01:24,389: WARNING/MainProcess] /home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-06-08 15:01:24,398: WARNING/MainProcess] /home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-06-08 15:02:32,500: INFO/MainProcess] Celery worker started
[2024-06-08 15:02:32,712: WARNING/MainProcess] /home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-06-08 15:02:32,720: INFO/MainProcess] Connected to redis://10.10.1.63:6379/0
[2024-06-08 15:02:32,721: WARNING/MainProcess] /home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-06-08 15:02:32,725: INFO/MainProcess] mingle: searching for neighbors
[2024-06-08 15:02:33,734: INFO/MainProcess] mingle: all alone
[2024-06-08 15:02:33,748: INFO/MainProcess] celery@cerelabs004 ready.
[2024-06-08 15:33:26,084: INFO/MainProcess] Task scrap_results[d3667b87-f3d6-451c-80da-5ecbeba323d0] received
[2024-06-08 15:33:26,086: INFO/ForkPoolWorker-3] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='mumbai restaurant images', use_cse_papi=True, max_links=20)", 'db': {'id': 6, 'scrap_query': 'mumbai restaurant images', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 3, 25), 'updated_at': datetime.datetime(2024, 6, 8, 10, 3, 25)}}
[2024-06-08 15:33:27,653: INFO/ForkPoolWorker-3] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='mumbai restaurant images', use_cse_papi=True, max_links=20)", 'db': {'id': 6, 'scrap_query': 'mumbai restaurant images', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 3, 25), 'updated_at': datetime.datetime(2024, 6, 8, 10, 3, 25)}}
[2024-06-08 15:33:27,824: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='upload.wikimedia.org', port=443): Max retries exceeded with url: /wikipedia/commons/7/7f/Mumbai_%28Bombay%29%2C_RTW_2012_%288403808043%29.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:27,887: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.architecturaldigest.in', port=443): Max retries exceeded with url: /photos/658e6749009d551799adc8d2/16:9/w_2560%2Cc_limit/Bawri%2520Interior%25205.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:28,139: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/60ab72ed-233b-4d5d-ad35-cf07ee61bd98.png'
[2024-06-08 15:33:28,200: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='preview.redd.it', port=443): Max retries exceeded with url: /z909ykr8s1sb1.jpg?auto=webp&s=bc4b62ee2c1df5f181edcdb6fffa9ff99f6dd8ea (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:28,274: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/ca2dc285-0c44-4c4b-92cb-ad22d4d785be.png'
[2024-06-08 15:33:28,805: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.wtravelmagazine.com', port=443): Max retries exceeded with url: /wp-content/uploads/2021/12/30.177.1-Best-20-Mumbai-Restaurants.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:28,848: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/25c3377c-2edd-470f-a49e-d2b01b823279.png'
[2024-06-08 15:33:28,961: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.gqindia.com', port=443): Max retries exceeded with url: /photos/633eb9208370bdb93eda1e3c/16:9/w_2560%2Cc_limit/One8-Commune_03.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:29,107: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='upload.wikimedia.org', port=443): Max retries exceeded with url: /wikipedia/commons/8/86/Indian_folk_Cuisine_Images_%28221%29.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:30,319: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='ambassadorindia.com', port=443): Max retries exceeded with url: /wp-content/uploads/2020/07/flavours-restaurant-the-ambassador-mumbai-1.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:30,377: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='i.redd.it', port=443): Max retries exceeded with url: /hdb759butt481.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:30,431: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='media.cntraveller.com', port=443): Max retries exceeded with url: /photos/611bf274c15cf5da489ed39b/16:9/w_2580,c_limit/roofsoho-house-mumbai-nov18-pr.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:30,551: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/5b127307-600b-4376-96d4-251c42550ecc.png'
[2024-06-08 15:33:32,007: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/7dc1b527-bdea-4c67-8d82-ed569633b042.png'
[2024-06-08 15:33:32,300: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.designpataki.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/12/New-In-Mumbai-Design-Guide-Latest-Restaurants-2-Design-Pataki-Feature-Image.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:33,707: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/b87a8d3c-1009-4148-844b-6e66c75baf1f.png'
[2024-06-08 15:33:33,852: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.cntraveller.in', port=443): Max retries exceeded with url: /photos/632debae1fa71362bb469295/16:9/w_2580,c_limit/Untitled%20design%20(22).jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:33,895: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.gqindia.com', port=443): Max retries exceeded with url: /photos/5e2eeafd7df8190008b4f942/master/pass/mumbai-restaurants-open-for-24-hours.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:33:33,899: INFO/ForkPoolWorker-3] Task scrap_results[d3667b87-f3d6-451c-80da-5ecbeba323d0] succeeded in 7.813900033997925s: None
[2024-06-08 15:36:07,545: INFO/MainProcess] Task scrap_results[a1f44be4-83ad-4384-bd1f-cbd16891b72d] received
[2024-06-08 15:36:07,547: INFO/ForkPoolWorker-3] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='mumbai restaurant images', use_cse_papi=True, max_links=20)", 'db': {'id': 7, 'scrap_query': 'mumbai restaurant images', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 6, 7), 'updated_at': datetime.datetime(2024, 6, 8, 10, 6, 7)}}
[2024-06-08 15:36:10,336: INFO/ForkPoolWorker-3] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='mumbai restaurant images', use_cse_papi=True, max_links=20)", 'db': {'id': 7, 'scrap_query': 'mumbai restaurant images', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 6, 7), 'updated_at': datetime.datetime(2024, 6, 8, 10, 6, 7)}}
[2024-06-08 15:36:10,717: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='upload.wikimedia.org', port=443): Max retries exceeded with url: /wikipedia/commons/7/7f/Mumbai_%28Bombay%29%2C_RTW_2012_%288403808043%29.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:10,763: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.architecturaldigest.in', port=443): Max retries exceeded with url: /photos/658e6749009d551799adc8d2/16:9/w_2560%2Cc_limit/Bawri%2520Interior%25205.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:10,819: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/6e559630-a169-4385-9a3e-b5127c1b1c4d.png'
[2024-06-08 15:36:10,875: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='preview.redd.it', port=443): Max retries exceeded with url: /z909ykr8s1sb1.jpg?auto=webp&s=bc4b62ee2c1df5f181edcdb6fffa9ff99f6dd8ea (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:11,169: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/b0f34b0e-dffb-40fc-9acc-cbb6eb4e1119.png'
[2024-06-08 15:36:11,660: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.wtravelmagazine.com', port=443): Max retries exceeded with url: /wp-content/uploads/2021/12/30.177.1-Best-20-Mumbai-Restaurants.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:11,945: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/d4769433-45b1-45c3-919e-32d50cd87430.png'
[2024-06-08 15:36:11,990: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.gqindia.com', port=443): Max retries exceeded with url: /photos/633eb9208370bdb93eda1e3c/16:9/w_2560%2Cc_limit/One8-Commune_03.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:12,132: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='upload.wikimedia.org', port=443): Max retries exceeded with url: /wikipedia/commons/8/86/Indian_folk_Cuisine_Images_%28221%29.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:13,090: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='ambassadorindia.com', port=443): Max retries exceeded with url: /wp-content/uploads/2020/07/flavours-restaurant-the-ambassador-mumbai-1.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:13,140: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='i.redd.it', port=443): Max retries exceeded with url: /hdb759butt481.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:13,217: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='media.cntraveller.com', port=443): Max retries exceeded with url: /photos/611bf274c15cf5da489ed39b/16:9/w_2580,c_limit/roofsoho-house-mumbai-nov18-pr.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:13,262: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/c9d2651d-bb54-46fe-878c-6bb4f9e8af61.png'
[2024-06-08 15:36:14,665: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/cd4aa217-7624-499a-b1ae-26d93e8543fa.png'
[2024-06-08 15:36:15,230: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.designpataki.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/12/New-In-Mumbai-Design-Guide-Latest-Restaurants-2-Design-Pataki-Feature-Image.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:16,525: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/4123a019-1460-4512-aab0-7294a1bca811.png'
[2024-06-08 15:36:16,598: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.cntraveller.in', port=443): Max retries exceeded with url: /photos/632debae1fa71362bb469295/16:9/w_2580,c_limit/Untitled%20design%20(22).jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:16,664: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='assets.gqindia.com', port=443): Max retries exceeded with url: /photos/5e2eeafd7df8190008b4f942/master/pass/mumbai-restaurants-open-for-24-hours.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 15:36:16,665: INFO/ForkPoolWorker-3] Task scrap_results[a1f44be4-83ad-4384-bd1f-cbd16891b72d] succeeded in 9.118954638001014s: None
[2024-06-08 16:12:22,382: INFO/MainProcess] Task scrap_results[aecbf1e9-4395-4653-a6a5-0b952ffbb6f3] received
[2024-06-08 16:12:22,384: INFO/ForkPoolWorker-3] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='pak', use_cse_papi=True, max_links=20)", 'db': {'id': 8, 'scrap_query': 'pak', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 42, 22), 'updated_at': datetime.datetime(2024, 6, 8, 10, 42, 22)}}
[2024-06-08 16:12:24,304: INFO/ForkPoolWorker-3] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='pak', use_cse_papi=True, max_links=20)", 'db': {'id': 8, 'scrap_query': 'pak', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 42, 22), 'updated_at': datetime.datetime(2024, 6, 8, 10, 42, 22)}}
[2024-06-08 16:14:07,809: INFO/MainProcess] Task scrap_results[9d6d367c-903c-4c4f-9e92-3474d52edc17] received
[2024-06-08 16:14:07,811: INFO/ForkPoolWorker-1] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='fdsfds', use_cse_papi=True, max_links=20)", 'db': {'id': 9, 'scrap_query': 'fdsfds', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 44, 7), 'updated_at': datetime.datetime(2024, 6, 8, 10, 44, 7)}}
[2024-06-08 16:14:09,137: INFO/ForkPoolWorker-1] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='fdsfds', use_cse_papi=True, max_links=20)", 'db': {'id': 9, 'scrap_query': 'fdsfds', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 10, 44, 7), 'updated_at': datetime.datetime(2024, 6, 8, 10, 44, 7)}}
[2024-06-08 16:14:10,330: WARNING/ForkPoolWorker-1] An error occurred: HTTPSConnectionPool(host='wallaroosfurnitureandmattresses.com', port=443): Max retries exceeded with url: /wp-content/uploads/2023/03/jaieren-jairen-fdsfds.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:10,850: WARNING/ForkPoolWorker-1] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/cde5474f-e422-4e58-921b-de6f1035afda.png'
[2024-06-08 16:14:11,627: WARNING/ForkPoolWorker-1] An error occurred: HTTPSConnectionPool(host='www.candyfavorites.com', port=443): Max retries exceeded with url: /blog/wp-content/uploads/Keystone%20Solid%20Surface%20Edge%20Treatments%20web.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:35,238: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.whirl-pak.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/09/StandUp-Bag-Family.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:36,256: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/42c073f8-4edc-49bd-a495-e85b4056eff9.png'
[2024-06-08 16:14:36,356: WARNING/ForkPoolWorker-3] Failed to retrieve image. HTTP Status code: 403
[2024-06-08 16:14:36,639: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='store.warlordgames.com', port=443): Max retries exceeded with url: /cdn/shop/products/WGB-LSS-11-Waffen-SS-75mm-PaK-40-anti-tank-gun-_1943-45_1.jpg?v=1665843597 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:36,681: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.whirl-pak.com', port=443): Max retries exceeded with url: /wp-content/uploads/2023/02/B01350-alt01P-scaled.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:37,327: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/fa12ecc1-4907-452c-948b-ffe858032e7f.png'
[2024-06-08 16:14:37,404: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.maryswholelife.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/03/Pad_Pak_04-scaled.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:37,461: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='store.warlordgames.com', port=443): Max retries exceeded with url: /cdn/shop/products/WGB-LHR-13-German-Heer-75mm-PaK-40-anti-tank-gun-_1943-45_3.jpg?v=1667826639 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:37,687: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='upload.wikimedia.org', port=443): Max retries exceeded with url: /wikipedia/commons/b/b8/Heeresgeschichtliches_Museum_Wien_7%2C5cm_PaK_40.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:37,731: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.whirl-pak.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/09/Thio-Bag-Family.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:38,535: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/56df08aa-6077-44df-bb17-9fed3c9375bb.png'
[2024-06-08 16:14:38,680: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.anandsweets.in', port=443): Max retries exceeded with url: /cdn/shop/products/SugarfreeMysorePak.png?v=1702379353&width=1946 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:39,188: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='api.army.mil', port=443): Max retries exceeded with url: /e2/c/images/2023/06/02/003a4c6b/original.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:39,898: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.bu.edu', port=443): Max retries exceeded with url: /files/2021/01/leadin-20-1576-PAK-046.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:39,941: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.whirl-pak.com', port=443): Max retries exceeded with url: /wp-content/uploads/2023/02/B01613-main-scaled.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:40,070: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.akingump.com', port=443): Max retries exceeded with url: /a/web/q7Kpgkqjgju5U5VaApXDv5/8nunZt/pak_elyssa_2160x1540.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:40,489: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.mecooks.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/01/IMGL0879-min-scaled.jpg (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:40,530: WARNING/ForkPoolWorker-3] An error occurred: HTTPSConnectionPool(host='www.whirl-pak.com', port=443): Max retries exceeded with url: /wp-content/uploads/2022/08/StandardBagWOStrip.png (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
[2024-06-08 16:14:41,504: WARNING/ForkPoolWorker-3] An error occurred: [Errno 2] No such file or directory: 'D:\\Coding\\internship\\image_scrapper\\temp/e31dc418-5564-427e-80ee-22efb7ca90a7.png'
[2024-06-08 16:14:41,507: INFO/ForkPoolWorker-3] Task scrap_results[aecbf1e9-4395-4653-a6a5-0b952ffbb6f3] succeeded in 139.12283277700044s: None
[2024-06-08 17:09:01,152: INFO/MainProcess] Task scrap_results[6416c6d6-4a0b-489d-ad0d-8c931473bfc1] received
[2024-06-08 17:09:01,153: INFO/ForkPoolWorker-3] Scrapping data. metadata: {'request': "ScrapSubmitRequest(query='dfdasfsfadsfsdfaffsaf', use_cse_papi=True, max_links=20)", 'db': {'id': 10, 'scrap_query': 'dfdasfsfadsfsdfaffsaf', 'scrap_data': None, 'status': 'InProgress', 'created_at': datetime.datetime(2024, 6, 8, 11, 39, 1), 'updated_at': datetime.datetime(2024, 6, 8, 11, 39, 1)}}
[2024-06-08 17:09:15,247: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,247: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,247: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,247: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,247: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,247: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,247: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: WARNING/ForkPoolWorker-3] An error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,248: ERROR/ForkPoolWorker-3] Error scraping data: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
Traceback (most recent call last):
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/worker.py", line 49, in scrap_save_search_results_worker
    search_results = google_search_using_cse_papi(search_text, max_urls)
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 148, in google_search_using_cse_papi
    return google_search_using_cse_papi(
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 148, in google_search_using_cse_papi
    return google_search_using_cse_papi(
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 148, in google_search_using_cse_papi
    return google_search_using_cse_papi(
  [Previous line repeated 17 more times]
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 139, in google_search_using_cse_papi
    response.raise_for_status()
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef
[2024-06-08 17:09:15,305: ERROR/ForkPoolWorker-3] Task scrap_results[6416c6d6-4a0b-489d-ad0d-8c931473bfc1] raised unexpected: AttributeError('__enter__')
Traceback (most recent call last):
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/worker.py", line 49, in scrap_save_search_results_worker
    search_results = google_search_using_cse_papi(search_text, max_urls)
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 148, in google_search_using_cse_papi
    return google_search_using_cse_papi(
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 148, in google_search_using_cse_papi
    return google_search_using_cse_papi(
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 148, in google_search_using_cse_papi
    return google_search_using_cse_papi(
  [Previous line repeated 17 more times]
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/scrap/helpers.py", line 139, in google_search_using_cse_papi
    response.raise_for_status()
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/customsearch/v1?q=dfdasfsfadsfsdfaffsaf&num=10&start=201&imgSize=huge&searchType=image&key=AIzaSyDYgOOODO_MHGrV28sIRPdrQ9GIaZlX4dU&cx=e74ae2f61bea249ef

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/.venv/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cerelabs/workarea/Aashish/PythonProjects/restaurant_menu_card_data_extractor/server/src/worker.py", line 71, in scrap_save_search_results_worker
    with get_db() as session:
AttributeError: __enter__
